title: 'Experience Design for Open Learning Environments'
description: Notes, thoughts and experiments about experience design for open learning environents from HibbittsDesign.org
taxonomies: [tags]
disqus_shortname: hibbittsdesignorg
owner:
  name: Paul Hibbitts
  email: 'paul@paulhibbitts.com'
  avatar: avatar.jpg
  bio: Educator/interaction designer creating better learning experiences for our connected world. Learning changes you.
  # Social networking links used in footer. Update and remove as you like.
  twitter: hibbittsdesign
  facebook:
  github: hibbittsdesign
  stackexchange:
  linkedin: paulhibbitts
  instagram:
  flickr:
  tumblr:
  # Entre the full URL to your Google+ profile.
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-19424343-18

metadata:
    description: 'Notes, thoughts and experiments about experience design for open learning environents from HibbittsDesign.org'
